particle_symbols = ["u, c, t, d, s, b, e, mu, tau, ve, vmu, vtau, g, gamma, Z, W, H"]

particles = [
    {"symbol":"u",
    "particle":"up quark",
    "mass": "2.2 MeV/c^2",
    "electric charge":"+2/3e",
    "spin":"1/2",
    "particle type":"fermion",
    "main class":"quark",
    "antiparticle":"up antiquark",
    "interactions":"strong, weak, electromagnetic, gravity"},

    {"symbol":"c",
    "particle":"charm quark",
    "mass": "1.275 GeV/c^2",
    "electric charge":"+2/3e",
    "spin":"1/2",
    "particle type":"fermion",
    "main class":"quark",
    "antiparticle":"Charm antiquark",
    "interactions":"strong, weak, electromagnetic, gravity"},

    {"symbol":"t",
    "particle":"top quark",
    "mass": "173 GeV/c^2",
    "electric charge":"+2/3e",
    "spin":"1/2",
    "particle type":"fermion",
    "main class":"quark",
    "antiparticle":"top antiquark",
    "interactions":"strong, weak, electromagnetic, gravity"},

    {"symbol":"d",
    "particle":"down quark",
    "mass": "4.7 MeV/c^2",
    "electric charge":"-1/3e",
    "spin":"1/2",
    "particle type":"fermion",
    "main class":"quark",
    "antiparticle":"down antiquark",
    "interactions":"strong, weak, electromagnetic, gravity"},

    {"symbol":"s",
    "particle":"strange quark",
    "mass": "95 MeV/c^2",
    "electric charge":"-1/3e",
    "spin":"1/2",
    "particle type":"fermion",
    "main class":"quark",
    "antiparticle":"strange antiquark",
    "interactions":"strong, weak, electromagnetic, gravity"},

    {"symbol":"b",
    "particle":"bottom quark",
    "mass": "4.18 GeV/c^2",
    "electric charge":"-1/3e",
    "spin":"1/2",
    "particle type":"fermion",
    "main class":"quark",
    "antinarticle":"bottom antiquark",
    "interactions":"strong, weak, electromagnetic, gravity"},

    {"symbol":"e",
    "particle":"electron",
    "mass": "510.10 keV/c^2 = 9.11e-31 kg",
    "electric charge":"-1.60e-19 C",
    "spin": "1/2",
    "particle type":"fermion",
    "main class":"lepton",
    "antiparticle":"positron",
    "interactions":"strong, weak, electromagnetic, gravity"},

    {"symbol":"mu",
    "particle":"muon",
    "mass": "105.66 MeV/c^2",
    "electric charge":"-1e",
    "spin":"1/2",
    "particle type":"fermion",
    "main class":"lepton",
    "antiparticle":"antimuon",
    "interactions":"weak, electromagnetic, gravity"},

    {"symbol":"tau",
    "particle":"tau",
    "mass": "1776.86 MeV/c^2",
    "electric charge":"-1e",
    "spin":"1/2",
    "particle type":"fermion",
    "main class":"lepton",
    "antiparticle":"antitau",
    "interactions":"weak, electromagnetic, gravity"},

    {"symbol":"ve",
    "particle":"electron neutrino",
    "mass": "small but non-zero",
    "electric charge":"0e",
    "spin":"1/2",
    "particle type":"fermion",
    "main class":"lepton",
    "antiparticle":"electron antineutrino",
    "interactions":"weak, gravity"},

    {"symbol":"vmu",
    "particle":"muon neutrino",
    "mass": "small but non-zero",
    "electric charge":"0e",
    "spin":"1/2",
    "particle type":"fermion",
    "main class":"lepton",
    "antiparticle":"muon antineutrino",
    "interactions":"weak, gravity"},

    {"symbol":"vtau",
    "particle":"tau neutrino",
    "mass": "small but non-zero",
    "electric charge":"0e",
    "spin":"1/2",
    "particle type":"fermion",
    "main class":"lepton",
    "antiparticle":"tau antineutrino",
    "interactions":"weak, gravity"},

    {"symbol":"g",
    "particle":"gluon",
    "mass": "0 (theoretical value) < 1.3 meV/c^2 (experimental limit)",
    "electric charge":"0e",
    "spin":"1",
    "particle type":"boson",
    "main class":"gaugeboson (vector bosons)",
    "antiparticle":"itself",
    "interactions":"strong"},

    {"symbol":"gamma",
    "particle":"photon",
    "mass": "0 (theoretical value) < 1.3e-18 eV/c^2 (experimental limit)",
    "electric charge":"0 (theoretical value) < 1e-35 e (experimental limit)",
    "spin":"1",
    "particle type":"boson",
    "main class":"gaugeboson (vector bosons)",
    "antiparticle":"itself",
    "interactions":"weak, electromagnetic, gravity"},

    {"symbol":"Z",
    "particle":"Z^0 boson",
    "mass": "91.19 GeV/c^2",
    "electric charge":"0e",
    "spin":"1",
    "particle type":"boson",
    "main class":"gaugeboson (vector bosons)",
    "antiparticle":"itself",
    "interactions":"weak"},

    {"symbol":"W",
    "particle":"W^+- boson",
    "mass":"80.38 GeV/c^2", 
    "electric charge":"+-1e",
    "spin":"1",
    "particle type":"boson",
    "main class":"gaugeboson (vector bosons)",
    "antiparticle":"itself",
    "interactions":"weak"},

    {"symbol":"H",
    "particle":"Higgs boson",
    "mass": "125.18 GeV/c^2",
    "electric charge":"0e",
    "spin":"0",
    "particle type":"boson",
    "main class":"scalar boson",
    "antiparticle":"itself",
    "interactions":"Higgs field"}
]

interactions_names = ["strong, weak, electromagnetic, gravity"]

interactions = [
    {"interaction":"strong",
    "definition":"the strong nuclear force holds most ordinary matter together because it confines quarks into hadron particles, such as the proton and neutron. In addition, it binds these neutrons and protons to create the atomic nuclei.",
    "scope":"about 1 fm",
    "relative strength":"1:1, i.e. the strongest force out of the four fundamental forces",
    "exchange particle":"gluons"},

    {"interaction":"electromagnetic",
    "definition":"the electromagnetic force is responsible for electromagnetic radiaiton, such as light.",
    "scope":"proportional to 1/r^2",
    "relative strength":"1:1e-2, i.e. the second strongest force force out of the four fundamental forces.",
    "exchange particle":"charged particles"},

    {"interaction":"weak",
    "definition":"the weak nuclear force is responsible for the radiactive decay of atoms.",
    "scope":"about 1e-3 fm",
    "relative strength":"1:1e-6, i.e. the penultimate weakest force out of the four fundamental forces.",
    "exchange particle":"W and Z bosons"},

    {"interaction":"gravity",
    "definition":"gravity is responsible for making all things with mass or energy gravitating toward one another.",
    "scope":"proportional to 1/r^2",
    "relative strength":"1:1e-31, i.e. the weakest force out of the four fundamental forces.",
    "exchange particle":"Unknown"}
]